[WIP] New issue Ebaty
devergroupio/sellthepeak-admin pull request #10
Opened 2020-07-09 07:16 UTC by trannhai1998

2020-07-09 12:17 UTC, devergroupio requested changes
Chỗ fs đó e dùng nossr vào chỗ mà sài package thử

2020-07-09 12:17 UTC, devergroupio commented on next.config.js
> +    config.node = {
Sao lại cần cái này?

2020-07-09 12:17 UTC, devergroupio commented on src/components/ExportExcel.tsx
> +interface IInfoChart {
Good!

2020-07-09 12:17 UTC, devergroupio commented on src/components/ExportExcel.tsx
> +  console.log([dataExcel]);
Nhớ bỏ hết console log khi chạy production

2020-07-09 12:17 UTC, devergroupio commented on src/components/ModalAddChart.tsx
> +          message: "Add new chart !",
Typo

2020-07-09 12:17 UTC, devergroupio commented on src/components/ModalAddChart.tsx
> +        notification.error({
Typo

2020-07-10 02:53 UTC, trannhai1998 commented on src/components/ExportExcel.tsx
> +interface IInfoChart {
có chi đâu mà good trời : )

2020-07-10 02:54 UTC, trannhai1998 commented on next.config.js
> +    config.node = {
dạ để dùng cái excel export . trong đó có cái xlsx cần config lỗi fs anh

2020-07-10 03:21 UTC, merged